@startuml

control User as Us
control ThriftServiceRunnber as Tsr
control ThriftUtil as Tu
control ZKClient as Zc
control IThriftInstanceProvider as Itip
control TServerSocket as Tss
control TServer as Ts

Us -> Tsr: startThriftServer

Tsr -> Tu: getServiceDefinitionClassName
Tsr <- Tu

Tsr -> Tu: getThriftZKPath
Tsr <- Tu

Tsr -> Tsr: loadZKConfigurationToSystemProperties

Tsr -> Tsr: startThriftServerImpl
Tsr -> Itip: getInstance
Tsr -> Tsr: getTProcessInstance
note right
通过反射获取Processor实例
end note

Tsr -> Tss: new TServerSocket
Tsr -> Ts:  new TServer
note right
根据支持的协议，分为IAuth
THsHaServer等,我们这里关注THsHaServer的实现
end note

Tsr -> Ts: serve(in another thread)

Tsr -> Zc: registerZKNode

@enduml
